/**
 * 疯狂水世界攻略数据
 * 数据来源：公开攻略整理，版本覆盖 S1-S7
 */

const GAME_DATA = {
  seasons: [
    { id: 's1', name: 'S1 赛季', desc: '黄螃蟹过渡，钩子阵容仍可用，国家队成型期' },
    { id: 's2', name: 'S2 赛季', desc: '红螃蟹成为分水岭，千代上线，钩子退出主流' },
    { id: 's3', name: 'S3 赛季', desc: '永生老乔登场，红螃蟹仍是核心海兽' },
    { id: 's4', name: 'S4 赛季', desc: '蓝血鲎+斗士崛起，老乔召唤队碾压射手队' },
    { id: 's5', name: 'S5 赛季', desc: '铁甲人鱼上线，龟龟流坦度进一步提升' },
    { id: 's6', name: 'S6 赛季', desc: '兰博核心体系回归，探案双子星联动登场' },
    { id: 's7', name: 'S7 赛季', desc: '等级上限100，超凡装备精炼，赛季商店更新' },
  ],

  seaBeasts: [
    {
      id: 'yellow-crab',
      name: '装甲鳖蟹（黄螃蟹）',
      rarity: '黄',
      seasons: ['s1'],
      desc: 'S1 最强过渡海兽，月卡可获取，一队必带',
      traits: ['基础攻击', '生命', '坦克闪避（前期可堆生命）'],
      tips: 'S1 未解锁红海兽时的最优选择，二队三队选高词条过渡海兽',
    },
    {
      id: 'red-crab',
      name: '红螃蟹',
      rarity: '红',
      seasons: ['s2', 's3'],
      desc: 'S2-S3 战力分水岭，收藏馆获取',
      traits: ['自由阵营攻击', '自由阵营暴击', '坦克闪避', '坦克减伤'],
      tips: '黄海兽优质词条 > 红海兽劣质词条，平均升级解锁全部词条',
    },
    {
      id: 'blue-horseshoe',
      name: '蓝血鲎',
      rarity: '红',
      seasons: ['s4', 's5', 's6', 's7'],
      desc: 'S4+ T0 海兽，龟龟流核心，赛季礼包获取',
      traits: ['坦克生命', '坦克减伤', '自由阵营攻击', '自由阵营伤害增加'],
      tips: '双队玩法一二队都带蓝血鲎，三队带高词条红螃蟹',
    },
    {
      id: 'iron-mermaid',
      name: '铁甲人鱼',
      rarity: '红',
      seasons: ['s5', 's6', 's7'],
      desc: 'S5 美人鱼联动新海兽，S5 赛季解锁兑换',
      traits: ['坦克相关', '自由者相关', '赛季专属词条'],
      tips: '配合探案双子星及龟龟流阵容，需随赛季解锁条件获取',
    },
    {
      id: 'dolphin',
      name: '海豚',
      rarity: '紫',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      desc: '平民过渡海兽，23 级解锁海兽系统后可选',
      traits: ['回血', '基础生命'],
      tips: '零氪前期 PVE/PVP 通用，后期替换为赛季红海兽',
    },
  ],

  teams: {
    f2p: [
      {
        id: 'national',
        name: '平民国家队',
        tag: '0氪首选',
        seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
        heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
        roles: ['主坦', '主C', '辅助', '副C/切后', '控制'],
        scene: '主线、资源副本、普通 BOSS、PVP 通用',
        logic: '山姆承伤嘲讽 → 兰博持续叠加伤害 → 老侃增伤减伤 → 蜜雪儿冰冻控场 → 屠夫切后排',
        priority: '升星：山姆 > 兰博 > 老侃 > 屠夫（3星停）',
      },
      {
        id: 'speed',
        name: '速推清场流',
        tag: '多波小怪',
        seasons: ['s1', 's2', 's3'],
        heroes: ['大嘴山姆', '一龙', '鬼火杰森', '米娅', '巫师老侃'],
        roles: ['主坦', 'AOE', '持续伤害', '治疗/增伤', '暴击辅助'],
        scene: '资源点防守、多波小怪、限时关卡',
        logic: '山姆聚怪 → 一龙 AOE 清场 → 杰森灼烧补伤害 → 米娅续航',
        priority: '过渡阵容，兰博抽到手后转国家队',
      },
      {
        id: 'boss',
        name: 'BOSS 持久流',
        tag: '高难首领',
        seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
        heroes: ['大嘴山姆', '兰博', '铁腿红魔', '神父欧玛', '蜜雪儿'],
        roles: ['主坦', '主C', '副坦', '治疗', '控制'],
        scene: '首领巢穴、深渊挑战、高难 BOSS',
        logic: '双坦分摊伤害 + 欧玛续航 + 蜜雪儿打断 BOSS 技能',
        priority: '腿魔、欧玛有则上，无则换回屠夫',
      },
      {
        id: 's6-f2p',
        name: 'S6 零氪铁三角',
        tag: 'S6 上分',
        seasons: ['s6', 's7'],
        heroes: ['大嘴山姆', '兰博', '巫师老侃', '千代', '蜜雪儿'],
        roles: ['主坦', '主C', '辅助', '副C', '控场'],
        scene: 'S6/S7 赛季 PVE/PVP/世界 BOSS',
        logic: '兰博+千代双输出，李忠诚 1 星可替补承伤',
        priority: '千代有则上，无则机器屠夫替代',
      },
    ],
    p2w: [
      {
        id: 'whale-national',
        name: '氪佬国家队',
        tag: '全赛季核心',
        seasons: ['s2', 's3', 's4', 's5', 's6', 's7'],
        heroes: ['兰博', '大嘴山姆', '巫师老侃', '雾隐千代', '懂王/大帝'],
        roles: ['主C', '主坦', '辅助', '刺客C', '红卡坦/输出'],
        scene: '竞技、跨服、高阶 PVP',
        logic: '千代锁后排 + 兰博叠伤害 + 大帝/懂王补坦度或输出',
        priority: '升星：懂王 > 兰博 > 老侃 > 千代 > 屠夫',
      },
      {
        id: 's4-summon',
        name: 'S4 老乔召唤队',
        tag: 'S4 T0',
        seasons: ['s4', 's5'],
        heroes: ['永生老乔', '斗士', '李忠诚', '萝莉', '大帝/盲僧'],
        roles: ['召唤核心', '必备坦克', '承伤', '辅助', '红卡补位'],
        scene: 'S4 竞技场、跨服对战',
        logic: '老乔 9 星+红能量，斗士 7 星提供坦度与奶 BUFF，完全碾压千代兰博队',
        priority: '老乔 9 星 > 斗士 7 星 > 李忠诚/萝莉 > 大帝',
      },
      {
        id: 's4-chiyo',
        name: 'S4 千代斗士队',
        tag: 'S4 次选',
        seasons: ['s4', 's5'],
        heroes: ['雾隐千代', '斗士', '兰博', '巫师老侃', '大帝/大嘴'],
        roles: ['主C', '核心坦', '副C', '辅助', '副坦'],
        scene: 'S4 内战、对抗召唤队',
        logic: '胜负看斗士坦度 vs 千代/兰博伤害增加属性',
        priority: '斗士专武、生命、减伤 > 千代六星专武三',
      },
      {
        id: 's4-lei',
        name: 'S4 雷教授法队',
        tag: '克制兰博',
        seasons: ['s4', 's5', 's6'],
        heroes: ['雷教授', '巫师老侃', '蜜雪儿', '斗士', '大嘴山姆'],
        roles: ['法伤核心', '辅助', '控场/回能', '坦克', '副坦'],
        scene: '内战克制兰博队、雷教授高星后主流',
        logic: '蜜雪儿帮雷教授吃老侃盾眩晕，保证大招完整输出',
        priority: '雷教授高星高技能强度后，蜜雪儿专武 60 级',
      },
      {
        id: 's5-twin',
        name: 'S5 探案双子星队',
        tag: '联动坦克',
        seasons: ['s5', 's6', 's7'],
        heroes: ['探案双子星', '兰博', '巫师老侃', '雾隐千代', '大帝'],
        roles: ['联动坦克', '主C', '辅助', '副C', '红坦'],
        scene: 'S5+ 高阶 PVP、美人鱼联动',
        logic: '双子星护盾+人鱼召唤，低氪三星即可，高氪追专武',
        priority: '双子星生命/闪避/减伤，随赛季更新进阶技能',
      },
    ],
  },

  /** 各赛季阵容推荐（按赛季浏览） */
  seasonTeams: {
    s1: {
      name: 'S1 赛季',
      meta: '黄螃蟹过渡，国家队成型，钩子仍可用',
      seaBeast: '装甲鳖蟹（黄螃蟹）+ 培育海豚',
      f2p: [
        {
          name: '开荒过渡队',
          tag: '0氪',
          heroes: ['大嘴山姆', '雷教授', '米娅', '鬼火杰森', '蜜雪儿'],
          roles: ['主坦', '输出', '治疗', '持续伤害', '控制'],
          logic: '系统送大嘴，新手五件套碎片多，第二周转国家队',
        },
        {
          name: '平民国家队',
          tag: '0氪核心',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: '第二周转盘抽兰博老侃后成型，S1-S7 通用',
        },
      ],
      p2w: [
        {
          name: '氪佬国家队',
          tag: '氪金',
          heroes: ['兰博', '懂王', '巫师老侃', '机器屠夫', '大帝'],
          roles: ['主C', '主坦', '辅助', '切后', '红卡'],
          logic: '懂王替换绿魔/大嘴，大帝补位',
        },
      ],
    },
    s2: {
      name: 'S2 赛季',
      meta: '红螃蟹分水岭，千代上线，钩子退出主流',
      seaBeast: '红螃蟹（收藏馆）一队必带',
      f2p: [
        {
          name: '平民国家队',
          tag: '0氪首选',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: 'S2 主流，红螃蟹词条优先洗自由者/坦克',
        },
        {
          name: '召唤二队',
          tag: '0氪二队',
          heroes: ['萝莉', '李忠诚', '小丑', '懂王', '雷教授'],
          roles: ['辅助', '承伤', '输出', '主坦', '法伤'],
          logic: '二三队召唤流，分散仇恨',
        },
      ],
      p2w: [
        {
          name: '氪佬国家队',
          tag: '氪金 T0',
          heroes: ['兰博', '懂王', '巫师老侃', '雾隐千代', '大帝'],
          roles: ['主C', '主坦', '辅助', '刺客C', '红坦'],
          logic: '千代 S2 第6天转盘获取，50抽保底',
        },
        {
          name: '千代核弹流',
          tag: '氪金爆发',
          heroes: ['雾隐千代', '兰博', '巫师老侃', '懂王', '大帝'],
          roles: ['主C', '副C', '辅助', '主坦', '补位'],
          logic: '红能量徽章开局大招，专武60秒杀一列',
        },
      ],
    },
    s3: {
      name: 'S3 赛季',
      meta: '永生老乔登场，白鲨当老大，利维坦待 S4',
      seaBeast: '红螃蟹主力，平均升级解锁9词条',
      f2p: [
        {
          name: '平民国家队',
          tag: '0氪',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: 'S3 仍是最稳 0 氪选择',
        },
      ],
      p2w: [
        {
          name: 'S3 最强五人',
          tag: '氪金 T0',
          heroes: ['北境大帝', '大嘴山姆', '兰博', '雾隐千代', '巫师老侃'],
          roles: ['红坦', '副坦', '主C', '副C', '辅助'],
          logic: '大帝+千代+兰博三核，可过渡到 S4',
        },
        {
          name: '老乔过渡召唤',
          tag: '氪金预备',
          heroes: ['永生老乔', '李忠诚', '萝莉', '铁僧', '大帝'],
          roles: ['召唤', '承伤', '辅助', '副坦', '红卡'],
          logic: 'S4 召唤队过渡，S4 斗士替换铁僧',
        },
        {
          name: '科技召唤二队',
          tag: '二队',
          heroes: ['雷教授', '机器屠夫', '蜜雪儿', '终结者', '大嘴山姆'],
          roles: ['法C', '切后', '控', '副坦', '主坦'],
          logic: 'S3 二队，S4 斗士替换小丑位',
        },
      ],
    },
    s4: {
      name: 'S4 赛季',
      meta: '蓝血鲎+斗士崛起，老乔召唤队碾压射手队',
      seaBeast: '蓝血鲎（一队）+ 红螃蟹（二队）',
      f2p: [
        {
          name: '平民国家队',
          tag: '0氪',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: 'S4 仍可用但竞技偏弱，推图够用',
        },
        {
          name: '雷教授过渡队',
          tag: '0氪克制',
          heroes: ['雷教授', '巫师老侃', '雾隐千代', '斗士', '大嘴山姆'],
          roles: ['法C', '辅助', '副C', '坦', '副坦'],
          logic: '千代锁兰博，雷教授压血线',
        },
      ],
      p2w: [
        {
          name: '老乔召唤队',
          tag: 'S4 T0',
          heroes: ['永生老乔', '斗士', '李忠诚', '萝莉', '大帝'],
          roles: ['召唤核心', '必备坦', '承伤', '辅助', '红卡'],
          logic: '老乔9星+红能量，完全碾压千代兰博队',
        },
        {
          name: '千代斗士队',
          tag: 'S4 次选',
          heroes: ['雾隐千代', '斗士', '兰博', '巫师老侃', '大帝'],
          roles: ['主C', '核心坦', '副C', '辅助', '副坦'],
          logic: '内战看斗士坦度 vs 千代/兰博增伤',
        },
        {
          name: '雷教授主流法队',
          tag: '高星法队',
          heroes: ['雷教授', '巫师老侃', '蜜雪儿', '斗士', '大嘴山姆'],
          roles: ['法C', '辅助', '控场/回能', '坦', '副坦'],
          logic: '蜜雪儿专武60级，帮雷教授吃老侃盾眩晕',
        },
      ],
    },
    s5: {
      name: 'S5 赛季',
      meta: '铁甲人鱼上线，探案双子星联动，召唤队成型',
      seaBeast: '蓝血鲎 + 铁甲人鱼（S5解锁）',
      f2p: [
        {
          name: '平民国家队',
          tag: '0氪',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: '0氪低氪仍不建议入手老乔，继续国家队',
        },
      ],
      p2w: [
        {
          name: '成型召唤队',
          tag: 'S5 T0',
          heroes: ['永生老乔', '斗士', '海王', '牢大', '李忠诚'],
          roles: ['召唤', '坦', '输出', '副C', '承伤'],
          logic: 'S5后最终成型，词条固定化省心',
        },
        {
          name: '探案双子星队',
          tag: '联动新队',
          heroes: ['探案双子星', '兰博', '巫师老侃', '雾隐千代', '大帝'],
          roles: ['联动坦', '主C', '辅助', '副C', '红坦'],
          logic: '美人鱼联动，双子星低氪三星可用',
        },
        {
          name: '老乔过渡（S5前）',
          tag: '过渡',
          heroes: ['永生老乔', '李忠诚', '萝莉', '斗士', '海王'],
          roles: ['召唤', '承伤', '辅助', '坦', '输出'],
          logic: 'S5前过渡，逐步替换为成型阵容',
        },
      ],
    },
    s6: {
      name: 'S6 赛季',
      meta: '兰博铁三角回归，战神小布登场',
      seaBeast: '蓝血鲎双队 + 高词条红螃蟹三队',
      f2p: [
        {
          name: 'S6 零氪铁三角',
          tag: '0氪 T0',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '千代', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '副C', '控场'],
          logic: '李忠诚1星可替补承伤，千代无则屠夫',
        },
        {
          name: '平民国家队',
          tag: '0氪备选',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '机器屠夫', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '切后', '控制'],
          logic: '无千代时的稳定选择',
        },
      ],
      p2w: [
        {
          name: 'S6 双C爆发',
          tag: '氪金',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '雾隐千代', '李忠诚'],
          roles: ['主坦', '主C', '辅助', '副C', '承伤'],
          logic: '兰博+千代双输出，PVP换初始能量阵',
        },
        {
          name: '探案双子星队',
          tag: '联动',
          heroes: ['探案双子星', '兰博', '巫师老侃', '雾隐千代', '大帝'],
          roles: ['联动坦', '主C', '辅助', '副C', '红坦'],
          logic: 'S6 联动坦克，护盾+人鱼召唤',
        },
      ],
    },
    s7: {
      name: 'S7 赛季',
      meta: '等级上限100，超凡装备精炼，赛季商店更新',
      seaBeast: '蓝血鲎 + 铁甲人鱼，博物馆强化全队',
      f2p: [
        {
          name: 'S6/S7 零氪铁三角',
          tag: '0氪 T0',
          heroes: ['大嘴山姆', '兰博', '巫师老侃', '千代', '蜜雪儿'],
          roles: ['主坦', '主C', '辅助', '副C', '控场'],
          logic: 'S7 延续 S6 最优 0 氪体系',
        },
      ],
      p2w: [
        {
          name: '氪佬双C队',
          tag: '氪金 T0',
          heroes: ['探案双子星', '兰博', '巫师老侃', '雾隐千代', '大帝'],
          roles: ['坦', '主C', '辅助', '副C', '红坦'],
          logic: '结合 S6 铁三角 + 联动坦克 + 精炼装备',
        },
        {
          name: '成型召唤队',
          tag: '氪金备选',
          heroes: ['永生老乔', '斗士', '海王', '牢大', '李忠诚'],
          roles: ['召唤', '坦', '输出', '副C', '承伤'],
          logic: '词条固定化，后期省心',
        },
      ],
    },
  },

  /** 种植体系 */
  planting: {
    intro: '选种厂产出种子 → 海上农田播种 → 收获农作物 → 厨房加工为副产品',
    tips: '赛季前期可关闭种子厂按需生产；居民订单刷新掉高耗种子订单；赛季末种子清零',
    crops: [
      { name: '小麦', tier: '低级', growTime: '约30分钟/块', output: '基础粮食', use: '维持居民饱腹，避免人口流失' },
      { name: '大豆', tier: '低级', growTime: '较快', output: '基础粮食/原料', use: '饱腹 + 厨房加工原料' },
      { name: '南瓜', tier: '中级', growTime: '中等', output: '蔬果原料', use: '厨房加工，居民订单' },
      { name: '高阶蔬果', tier: '高级', growTime: '较长', output: '高级食材', use: '海产/农作物厨房加工，换建设经验与材料' },
    ],
    buildings: ['选种厂', '海上农田', '农作物厨房'],
    seedUses: ['居民订单', '联盟捐献', '海兽进阶', '博物馆寻宝', '港口贸易', '不差钱商人', '红卡转盘', '联盟募兵'],
  },

  /** 生产体系 */
  production: {
    intro: '各类工厂加工原材料为副产品，副产品是赛季核心消耗资源',
    tips: '优先投入：海兽进阶 > 博物馆5星 > 港口贸易 > 联盟捐献；委派生产英雄可加速40-50%',
    categories: [
      {
        type: '渔业加工',
        icon: '🐟',
        buildings: [
          { name: '钓鱼台', products: ['鲜鱼'], use: '切鱼厂原料' },
          { name: '切鱼厂', products: ['生鱼片', '鱼胶', '鱼油'], use: '居民订单、贸易' },
          { name: '海产厨房', products: ['鱼饼汉堡', '炸鱼薯条', '香煎鱼排', '各类海鲜料理'], use: '居民订单、经验材料' },
        ],
      },
      {
        type: '农业加工',
        icon: '🌾',
        buildings: [
          { name: '选种厂', products: ['小麦种子', '大豆种子', '南瓜种子等'], use: '农田播种' },
          { name: '农作物厨房', products: ['面包', '面点', '蔬果副产品等'], use: '订单/海兽进阶/博物馆' },
        ],
      },
      {
        type: '工业制造',
        icon: '🏭',
        buildings: [
          { name: '材料厂', products: ['基础材料'], use: '建筑升级' },
          { name: '建材厂', products: ['建材'], use: '基地扩建' },
          { name: '金属厂', products: ['金属'], use: '装备/建筑' },
          { name: '海水提取厂', products: ['海水制品'], use: '工业原料' },
          { name: '日用品厂', products: ['日用品'], use: '居民需求/订单' },
          { name: '服装作坊', products: ['服装'], use: '订单/贸易' },
          { name: '家具作坊', products: ['家具'], use: '基地/订单' },
          { name: '玩具厂', products: ['玩具'], use: '订单' },
          { name: '药品厂', products: ['药品'], use: '订单/生存' },
        ],
      },
    ],
    heroBonus: [
      { hero: '海森堡', skill: '农作物厨房+药品厂', bonus: '最高+50%' },
      { hero: '喷火莉莉', skill: '材料厂+海水提取厂', bonus: '最高+50%' },
      { hero: '战神小布', skill: '切鱼厂+海产厨房', bonus: '最高+40%' },
      { hero: '珍妮', skill: '服装作坊+饰品厂', bonus: '最高+40%' },
      { hero: '警员鲍勃', skill: '日用品厂', bonus: '最高+40%' },
    ],
  },

  /** 海兽体系（培育类型 + 赛季海兽 + 品质） */
  seaBeastSystem: {
    unlock: '23级解锁海兽培育室，最多同时培养4种（培育室3级可同时上阵3只）',
    qualities: [
      { name: '稀有（蓝）', traits: 0, wash: false, note: '直接放生，返20紫碎片' },
      { name: '史诗（紫）', traits: 1, wash: false, note: '前期过渡，后期放生返100金碎片' },
      { name: '传说（金）', traits: 2, wash: true, note: '主力培养，放生返200红碎片' },
      { name: '超凡（红）', traits: 3, wash: true, note: 'S2解锁，极品词条上限最高' },
    ],
    battleTypes: [
      {
        id: 'dolphin-battle',
        name: '海豚',
        icon: '🐬',
        type: '辅助/治疗',
        skill: '为随机3名英雄回血+减伤',
        cd: '开战5秒，冷却8秒',
        scene: '万金油，所有阵容可用，0氪前期首选',
        tier: 'T1',
      },
      {
        id: 'shark',
        name: '鲨鱼',
        icon: '🦈',
        type: '物理输出',
        skill: '物理伤害+概率重伤减疗',
        cd: '开战6秒，冷却9秒',
        scene: '克制欧玛与生命回收词条',
        tier: 'T2',
      },
      {
        id: 'octopus',
        name: '章鱼',
        icon: '🐙',
        type: '控制',
        skill: '能量伤害+概率眩晕',
        cd: '开战6秒，冷却9秒',
        scene: '概率控场，效果不稳定看运气',
        tier: 'T2',
      },
      {
        id: 'crab-battle',
        name: '鳌蟹',
        icon: '🦀',
        type: '防护/免控',
        skill: '全体双抗+护盾，双C 5秒免疫控制',
        cd: '开战4秒，冷却10秒',
        scene: '版本最强培育海兽，国家队必养',
        tier: 'T0',
      },
    ],
    seasonTypes: [
      { name: '装甲鳖蟹（黄螃蟹）', season: 'S1', rarity: '黄', get: '月卡', role: 'S1过渡最强' },
      { name: '红螃蟹', season: 'S2-S3', rarity: '红', get: '收藏馆', role: '战力分水岭' },
      { name: '蓝血鲎', season: 'S4+', rarity: '红', get: '赛季礼包', role: '龟龟流T0' },
      { name: '铁甲人鱼', season: 'S5+', rarity: '红', get: '联动/赛季商店', role: '联动坦配装' },
      { name: '白鲨', season: 'S3', rarity: '-', get: '舰队老大', role: 'S3收益最大化' },
      { name: '利维坦', season: 'S4+', rarity: '-', get: '舰队老大', role: 'S4阵容成型后更换' },
    ],
    cultivateTips: [
      '平均升级3只海兽，30/65/100级解锁全部9词条',
      '满阶20阶，更换海兽养成进度可继承（词条不保留）',
      '黄海兽好词条 > 红海兽烂词条',
      '洗练仅金/红品质，2条极品词条即可用',
    ],
  },

  traitGuide: {
    output: {
      title: '输出核心词条（兰博/千代）',
      priority: ['自由阵营攻击', '射手攻击', '自由阵营暴击', '射手暴击', '自由阵营攻速', '自由阵营伤害增加', '自由阵营生命回收'],
      note: '攻击/生命/技能强度为乘法叠加，优先分散在不同系统获取',
    },
    tank: {
      title: '前排坦克词条（大嘴/斗士）',
      priority: ['坦克闪避（毕业）', '坦克减伤', '坦克暴击抵抗', '坦克护甲', '坦克生命值', '坦克抗性'],
      note: 'S1 平民可先堆生命，闪避洗出后不建议随意更换',
    },
    support: {
      title: '辅助词条（老侃/蜜雪儿）',
      priority: ['技能强度', '冷却缩减', '生命', '减伤', '攻击速度（蜜雪儿）'],
      note: '老侃堆技能强度增伤，蜜雪儿堆攻速/生命/减伤保生存',
    },
    badge: {
      title: '徽章通用原则',
      priority: ['黑铁及以上才有词条', '攻击属性乘法收益最高', '坦克优先闪避/生命/减伤', '不随机兑换徽章'],
      note: '闯关挂机每 2 小时获得 1 个徽章，层数越高品质越好',
    },
  },

  heroes: [
    {
      id: 'sam',
      name: '大嘴山姆',
      rarity: '橙',
      faction: '兄弟会',
      role: '坦克',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: '登录赠送，零氪必拿',
      positioning: '前排嘲讽+承伤，3星解锁全场嘲讽质变',
      skills: {
        priority: ['1技能 嘲讽', '4技能 嘲讽增强', '2技能', '3技能'],
        desc: '1技能嘲讽聚怪，4技能增强后嘲讽全场；三星前仅嘲讽周围2格',
      },
      badges: ['闪避（目标75%）', '生命', '减伤', '双抗'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '抗压头盔 / 护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['闪避 > 生命 > 减伤 > 双抗'],
      seaBeast: '优先坦克闪避词条，S4+ 配蓝血鲎',
      starPriority: '3星必满（解锁嘲讽），4星看资源',
      f2p: true,
      p2w: true,
      tips: '与机器屠夫配合可保C切C；对角线站位防屠夫钩',
    },
    {
      id: 'rambo',
      name: '兰博',
      rarity: '橙',
      faction: '自由者',
      role: '射手',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: '开服第二周幸运转盘、68元战令、招募',
      positioning: '版本最强主C，战斗越久伤害越高，持续输出天花板',
      skills: {
        priority: ['1技能 热血', '4技能 热血增强', '2技能', '3技能'],
        desc: '1技能叠攻击攻速，4技能为全队提升攻速；主点1、4',
      },
      badges: ['攻击速度', '暴击', '生命回收', '攻击'],
      equipment: {
        weapon: '穿甲机枪 / 能量炮',
        armor: '护盾战衣',
        accessory: '动力大锤 / 等离子大剑',
      },
      traits: ['攻速 ≥0.93', '暴击 ≥20%', '生命回收 ≥20%', '攻击'],
      seaBeast: '自由阵营攻击/暴击/攻速，洗2条极品即可',
      starPriority: '3星→4星→5星，全队最高优先级',
      f2p: true,
      p2w: true,
      tips: '攻速控在1.0-1.2；PVP可换初始能量阵',
    },
    {
      id: 'kan',
      name: '巫师老侃',
      rarity: '橙',
      faction: '自由者',
      role: '法师/辅助',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: '第二周转盘、招募',
      positioning: '全队增伤+减伤+暴击BUFF，适配所有阵容',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '提供暴击率与增伤，同时具备减伤效果',
      },
      badges: ['技能强度', '生命', '减伤', '冷却'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['技能强度 > 生命 > 减伤 > 冷却'],
      seaBeast: '自由阵营相关词条，辅助向',
      starPriority: '3星必满，4星随缘',
      f2p: true,
      p2w: true,
      tips: '和主C放一起防机器屠夫钩；冰寒芯片适合纯法强老侃',
    },
    {
      id: 'butcher',
      name: '机器屠夫',
      rarity: '橙',
      faction: '科技派',
      role: '战士',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6'],
      tier: 'T1',
      obtain: '招募',
      positioning: '副C+切后排，钩子拉最远敌人集火',
      skills: {
        priority: ['1技能 钩子', '4技能', '2技能', '3技能'],
        desc: '钩子技能拉取敌方关键单位，配合召唤物集火秒杀',
      },
      badges: ['生命', '减伤', '攻击', '穿透'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['生命 > 减伤 > 攻击 > 穿透'],
      seaBeast: '科技派词条（非国家队优先时次要）',
      starPriority: '3星即停，绝不继续升',
      f2p: true,
      p2w: false,
      tips: '三星够用；与大嘴配合实现保C切C',
    },
    {
      id: 'michelle',
      name: '蜜雪儿',
      rarity: '橙',
      faction: '自由者',
      role: '法师/控制',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T1',
      obtain: '新手五件套、活动',
      positioning: '冰冻控场+回能，万金油辅助',
      skills: {
        priority: ['1技能 冰城', '4技能 冰城增强', '2技能', '3技能'],
        desc: '随机冰冻3敌人2.4秒；增强后恢复友军16能量',
      },
      badges: ['攻击速度', '生命', '伤害减免'],
      equipment: {
        weapon: '能量炮',
        armor: '抗压头盔',
        accessory: '破甲刃',
      },
      traits: ['攻速 > 生命 > 减伤（不堆输出）'],
      seaBeast: '辅助向，优先生存词条',
      starPriority: '靠活动/自选，专武41级即可',
      f2p: true,
      p2w: true,
      tips: 'S4雷教授队核心挂件；专武60级降敌方能量',
    },
    {
      id: 'chiyo',
      name: '雾隐千代',
      rarity: '红',
      faction: '自由者',
      role: '射手',
      seasons: ['s2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: 'S2第6天转盘（50抽保底）、皮肤/活动兑换',
      positioning: '后排杀手，混合伤害刺客型射手',
      skills: {
        priority: ['4技能 破影击增强', '2技能 提高攻击', '3技能 提高攻速', '1技能 大招'],
        desc: '4技能强化普攻+免伤为核心；1技能升级收益低（技能强度成长低）',
      },
      badges: ['伤害增加', '暴击', '攻击', '抗性穿透', '命中（S3+）'],
      equipment: {
        weapon: '榴弹发射器',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['伤害增加 > 暴击 > 攻击 > 抗性穿透'],
      seaBeast: '自由者/射手攻击、暴击、伤害增加',
      starPriority: '3星上场，6星专武三级质变',
      f2p: false,
      p2w: true,
      tips: 'S3+普攻流为主，核弹流已淘汰；需50暴击抵抗防对位千代',
    },
    {
      id: 'emperor',
      name: '懂王/大帝',
      rarity: '红',
      faction: '兄弟会',
      role: '坦克/输出',
      seasons: ['s2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: '高阶招募、活动',
      positioning: '红卡坦/输出，氪佬国家队核心',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '高坦度或输出补位，反伤芯片适合肉大帝',
      },
      badges: ['闪避', '生命', '减伤', '反伤相关'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['生命 > 减伤 > 闪避 > 双抗'],
      seaBeast: '坦克闪避/减伤/生命',
      starPriority: '氪佬高优先级，替换大嘴或补位',
      f2p: false,
      p2w: true,
      tips: '反伤芯片归宿；S4召唤队/千代队均可带',
    },
    {
      id: 'fighter',
      name: '斗士',
      rarity: '红',
      faction: '自由者',
      role: '坦克',
      seasons: ['s4', 's5', 's6', 's7'],
      tier: 'T0',
      obtain: 'S4赛季',
      positioning: 'S4+ 必备核心坦克，生命+增益BUFF',
      skills: {
        priority: ['4技能', '1技能', '2技能', '3技能'],
        desc: '提供全队坦度与奶BUFF，专武等级影响内战胜负',
      },
      badges: ['生命', '伤害减免', '减伤', '技能强度'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '护盾战衣 / 抗压头盔',
        accessory: '破甲刃',
      },
      traits: ['生命 > 减伤 > 双抗 > 技能强度'],
      seaBeast: '坦克生命/减伤，配蓝血鲎',
      starPriority: 'S4氪佬7星，专武拉满',
      f2p: false,
      p2w: true,
      tips: 'S4内战核心；坦度和奶BUFF决定队伍上限',
    },
    {
      id: 'immortal-joe',
      name: '永生老乔',
      rarity: '红',
      faction: '自由者',
      role: '召唤',
      seasons: ['s3', 's4', 's5'],
      tier: 'T0',
      obtain: 'S3赛季',
      positioning: 'S4 召唤队核心，9星+红能量',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '召唤流核心，S4环境碾压射手输出队',
      },
      badges: ['技能强度', '生命', '减伤', '初始能量（红能量徽章）'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['技能强度 > 生命 > 减伤'],
      seaBeast: '蓝血鲎，召唤相关词条',
      starPriority: '9星+红能量为S4顶配',
      f2p: false,
      p2w: true,
      tips: 'S4第一梯队；搭配斗士+李忠诚+萝莉',
    },
    {
      id: 'loyal-li',
      name: '李忠诚',
      rarity: '橙',
      faction: '兄弟会',
      role: '坦克',
      seasons: ['s4', 's5', 's6', 's7'],
      tier: 'T1',
      obtain: 'S4赛季、招募',
      positioning: '承伤补位，1星即可过渡上场',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '替补坦，资源不够升高阶也可临时使用',
      },
      badges: ['生命', '减伤', '双抗'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['生命 > 减伤 > 双抗'],
      seaBeast: '坦克词条',
      starPriority: '1星可用，按需升星',
      f2p: true,
      p2w: true,
      tips: 'S6零氪阵容承伤补位首选',
    },
    {
      id: 'professor-lei',
      name: '雷教授',
      rarity: '橙',
      faction: '科技派',
      role: '法师',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6'],
      tier: 'T1',
      obtain: '招募、新手过渡',
      positioning: '法伤核心，S4高星后可做主C',
      skills: {
        priority: ['1技能 大招', '4技能', '2技能', '3技能'],
        desc: '高星高技能强度后可独立灌伤；配合千代压制兰博',
      },
      badges: ['技能强度', '暴击', '攻击', '冷却'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['技能强度 > 暴击 > 攻击'],
      seaBeast: '科技派/法师词条',
      starPriority: '过渡用；S4高星后重点培养',
      f2p: true,
      p2w: true,
      tips: 'S4雷教授+蜜雪儿+斗士克制兰博队',
    },
    {
      id: 'dragon',
      name: '一龙',
      rarity: '橙',
      faction: '兄弟会',
      role: '射手',
      seasons: ['s1', 's2', 's3'],
      tier: 'T2',
      obtain: '招募',
      positioning: 'AOE清场，过渡阵容核心',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '大范围AOE，配合大嘴聚怪清场',
      },
      badges: ['攻击', '暴击', '攻速'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '抗压头盔',
        accessory: '等离子大剑',
      },
      traits: ['攻击 > 暴击 > 攻速'],
      seaBeast: '兄弟会攻击/射手词条',
      starPriority: '过渡用，兰博到手后转国家队',
      f2p: true,
      p2w: false,
      tips: '速推清场流核心；后期可作二队',
    },
    {
      id: 'mia',
      name: '米娅',
      rarity: '橙',
      faction: '兄弟会',
      role: '辅助',
      seasons: ['s1', 's2', 's3'],
      tier: 'T2',
      obtain: '招募、新手五件套',
      positioning: '群体治疗+团队增伤',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '速推流续航保障',
      },
      badges: ['生命', '技能强度', '减伤'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['生命 > 技能强度 > 减伤'],
      seaBeast: '兄弟会相关',
      starPriority: '过渡用',
      f2p: true,
      p2w: false,
      tips: '新手五件套之一，后期二队',
    },
    {
      id: 'jason',
      name: '鬼火杰森',
      rarity: '橙',
      faction: '兄弟会',
      role: '战士',
      seasons: ['s1', 's2', 's3'],
      tier: 'T2',
      obtain: '招募、新手五件套',
      positioning: '持续灼烧，填补AOE真空期',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '速推流持续伤害',
      },
      badges: ['攻击', '生命回收', '攻速'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '抗压头盔',
        accessory: '破甲刃',
      },
      traits: ['攻击 > 生命回收 > 攻速'],
      seaBeast: '兄弟会攻击',
      starPriority: '过渡用',
      f2p: true,
      p2w: false,
      tips: '新手五件套，碎片易得',
    },
    {
      id: 'red-leg',
      name: '铁腿红魔',
      rarity: '橙',
      faction: '兄弟会',
      role: '坦克',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T1',
      obtain: '招募',
      positioning: '副坦，BOSS战双坦体系',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '与山姆分摊伤害，稳固防线',
      },
      badges: ['生命', '减伤', '双抗'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['减伤 > 生命 > 双抗'],
      seaBeast: '坦克词条',
      starPriority: '3星够用',
      f2p: true,
      p2w: false,
      tips: 'BOSS持久流副坦；可带能量恢复阵',
    },
    {
      id: 'father-oma',
      name: '神父欧玛',
      rarity: '橙',
      faction: '自由者',
      role: '辅助/治疗',
      seasons: ['s1', 's2', 's3', 's4', 's5', 's6', 's7'],
      tier: 'T1',
      obtain: '招募',
      positioning: '长效治疗+全队增伤',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: 'BOSS战续航核心',
      },
      badges: ['生命', '技能强度', '减伤', '冷却'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['技能强度 > 生命 > 减伤'],
      seaBeast: '辅助向',
      starPriority: 'BOSS队按需培养',
      f2p: true,
      p2w: false,
      tips: '高难副本延长团队续航',
    },
    {
      id: 'terminator',
      name: '终结者',
      rarity: '橙',
      faction: '科技派',
      role: '坦克',
      seasons: ['s2', 's3', 's4', 's5', 's6'],
      tier: 'T1',
      obtain: 'S2赛季、招募',
      positioning: '副坦+反伤+续航，深渊专用',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: 'BOSS战替代屠夫位置',
      },
      badges: ['减伤', '生命', '抗性', '生命回收'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '等离子大剑',
      },
      traits: ['减伤 > 生命 > 抗性'],
      seaBeast: '坦克词条',
      starPriority: '3星够用',
      f2p: true,
      p2w: false,
      tips: '深渊挑战副坦选择',
    },
    {
      id: 'hook',
      name: '钩子',
      rarity: '紫',
      faction: '兄弟会',
      role: '战士',
      seasons: ['s1', 's2'],
      tier: 'T3',
      obtain: '早期招募',
      positioning: 'S1-S2过渡，S2后退出主流',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '早期过渡，红螃蟹上线后被淘汰',
      },
      badges: ['生命', '攻击'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '抗压头盔',
        accessory: '破甲刃',
      },
      traits: ['生命 > 攻击'],
      seaBeast: '坦克词条（与大嘴不同阵营）',
      starPriority: '不建议投入',
      f2p: true,
      p2w: false,
      tips: 'S2后转国家队，资源可回收',
    },
    {
      id: 'twins',
      name: '探案双子星',
      rarity: '红',
      faction: '自由者',
      role: '坦克',
      seasons: ['s5', 's6', 's7'],
      tier: 'T0',
      obtain: 'S5/S6美人鱼联动转盘',
      positioning: '联动坦克，护盾+人鱼召唤，随赛季进阶技能',
      skills: {
        priority: ['1技能 护盾', '4技能', '2技能', '3技能'],
        desc: '多种功能性人鱼召唤，特殊赛季更新进阶机制',
      },
      badges: ['生命', '闪避', '减伤'],
      equipment: {
        weapon: '脉冲步枪',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['生命 > 闪避 > 减伤'],
      seaBeast: '铁甲人鱼搭配，坦克词条',
      starPriority: '低氪三星，高氪追专武',
      f2p: false,
      p2w: true,
      tips: 'S5美人鱼联动核心；替代或补充大嘴',
    },
    {
      id: 'loli',
      name: '萝莉',
      rarity: '橙',
      faction: '自由者',
      role: '辅助',
      seasons: ['s4', 's5'],
      tier: 'T1',
      obtain: 'S4赛季',
      positioning: '老乔召唤队辅助位',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '召唤队配套辅助',
      },
      badges: ['技能强度', '生命', '冷却'],
      equipment: {
        weapon: '能量炮',
        armor: '护盾战衣',
        accessory: '破甲刃',
      },
      traits: ['技能强度 > 生命 > 冷却'],
      seaBeast: '辅助/召唤相关',
      starPriority: '召唤队按需培养',
      f2p: false,
      p2w: true,
      tips: 'S4老乔召唤队标配',
    },
    {
      id: 'blind-monk',
      name: '盲僧',
      rarity: '红',
      faction: '自由者',
      role: '战士',
      seasons: ['s4', 's5'],
      tier: 'T1',
      obtain: 'S4赛季',
      positioning: '老乔召唤队替代大帝',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: '召唤队补位，替代大帝方案',
      },
      badges: ['攻击', '暴击', '生命'],
      equipment: {
        weapon: '等离子大剑',
        armor: '护盾战衣',
        accessory: '动力大锤',
      },
      traits: ['攻击 > 暴击 > 生命'],
      seaBeast: '输出词条',
      starPriority: '氪佬召唤队选配',
      f2p: false,
      p2w: true,
      tips: '老乔+斗士+李忠诚+萝莉+盲僧',
    },
    {
      id: 'xiao-bu',
      name: '战神小布',
      rarity: '红',
      faction: '自由者',
      role: '战士',
      seasons: ['s6', 's7'],
      tier: 'T1',
      obtain: 'S6赛季',
      positioning: 'S6新英雄，高爆发战士',
      skills: {
        priority: ['1技能', '4技能', '2技能', '3技能'],
        desc: 'S6赛季新内容，具体搭配随版本更新',
      },
      badges: ['攻击', '暴击', '伤害增加'],
      equipment: {
        weapon: '等离子大剑',
        armor: '护盾战衣',
        accessory: '动力大锤',
      },
      traits: ['攻击 > 暴击 > 伤害增加'],
      seaBeast: '自由者攻击/暴击',
      starPriority: '新赛季按需投入',
      f2p: false,
      p2w: true,
      tips: 'S6赛季新英雄，关注后续攻略更新',
    },
  ],

  /** 每日 / 常规任务 */
  tasks: {
    intro: '合理规划每日任务，是零氪攒资源、稳步提升战力的关键。',
    daily: [
      { name: '领取挂机奖励', tag: '必做', desc: '离线自动产资源，每天领 1 次' },
      { name: '收潜水 / 拾荒资源', tag: '必做', desc: '每日清挂机、潜水、拾荒产出' },
      { name: '完成每日任务', tag: '必做', desc: '活跃度、钻石、招募券主要来源' },
      { name: '居民订单', tag: '必做', desc: '刷新掉高耗种子订单，按需完成' },
      { name: '刷新贸易货轮', tag: '推荐', desc: '稳定给藏品与经验，每日顺手清' },
      { name: '推主线关卡', tag: '推荐', desc: '解锁玩法、提升徽章挂机品质' },
      { name: '联盟捐献', tag: '推荐', desc: '每日 20 次，换核心碎片与蓝图' },
      { name: '联盟互助', tag: '推荐', desc: '帮助他人加速，获取回报' },
      { name: '港口贸易', tag: '推荐', desc: '藏品和经验，别省材料' },
      { name: '博物馆寻宝', tag: '可选', desc: '5 星后收益更好，前期可砸加速' },
    ],
    weekly: [
      { name: '兰博 / 老侃转盘', tag: '第二周', desc: '预留 1.5 万钻石参与' },
      { name: '联盟募兵', tag: '每周', desc: '提交资源换贡献' },
      { name: '海兽培育', tag: '23级+', desc: '周一海豚、鳌蟹轮换培育' },
      { name: '竞技场挑战', tag: 'PVP', desc: '23:59 前完成，避免结算中断' },
    ],
    tips: [
      '居民订单见到种子消耗大的产品直接刷新跳过',
      '钻石不抽普通池，留给转盘和 5 折蓝图',
      '每日 5 分钟：挂机 → 任务 → 订单 → 货轮 → 主线',
    ],
  },

  seasonSeaBeastGuide: [
    { season: 'S1', main: '黄螃蟹（一队）', sub: '高词条过渡海兽', note: '月卡平民首选，堆基础攻击/生命' },
    { season: 'S2-S3', main: '红螃蟹（一队必带）', sub: '二队有条件也带红螃蟹', note: '钩子退出主流，黄海兽好词条>红海兽烂词条' },
    { season: 'S4-S5', main: '蓝血鲎（一队）', sub: '二队红螃蟹/蓝血鲎', note: '龟龟流崛起，斗士+蓝血鲎是版本答案' },
    { season: 'S5+', main: '蓝血鲎 + 铁甲人鱼', sub: '三队高词条红螃蟹', note: '铁甲人鱼S5解锁，双队都带蓝血鲎' },
    { season: '全赛季', main: '平均升级3只海兽', sub: '解锁9词条拿满加成', note: '满阶20阶，更换海兽养成可继承' },
  ],

  tips: [
    '万能碎片只给核心：山姆 > 兰博 > 老侃 > 屠夫（3星停）',
    '出战英雄优先点 1、4 技能；生产英雄点 2、3 技能',
    '装备：武器 > 胸甲 > 饰品，+5前无脑升，+7后用保护石',
    '海兽词条：阵营词条 > 职业词条 > 个人词条',
    '攻击/生命/技能强度乘法叠加，优先分散在不同系统',
    '钻石预留1.5万给第二周兰博/老侃转盘',
    '23级解锁海兽，平民前期选海豚过渡',
    '徽章闯关挂机每2小时1个，层数越高品质越好',
  ],
};

if (typeof module !== 'undefined') module.exports = GAME_DATA;
